name: untitled
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  get: ^4.6.6
  flutter_rating_bar: ^4.0.1
  step_progress_indicator: ^1.0.2
  sqflite: ^2.3.3+1
  path: ^1.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/imgs/
    - assets/fonts/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500

    - family: MyFlutterApp
      fonts:
        - asset: assets/fonts/MyFlutterApp.ttf
    - family: MyFlutterApp2
      fonts:
        - asset: assets/fonts/MyFlutterApp2.ttf
    - family: MyFlutterApp3
      fonts:
        - asset: assets/fonts/MyFlutterApp3.ttf
    - family: MyFlutterApp5
      fonts:
        - asset: assets/fonts/MyFlutterApp5.ttf
    - family: MyFlutterApp6
      fonts:
        - asset: assets/fonts/MyFlutterApp6.ttf
    - family: MyFlutterApp4
      fonts:
        - asset: assets/fonts/MyFlutterApp4.ttf
    - family: MyFlutterApp7
      fonts:
        - asset: assets/fonts/MyFlutterApp7.ttf
    - family: MyFlutterApp8
      fonts:
        - asset: assets/fonts/MyFlutterApp8.ttf
    - family: MyFlutterApp9
      fonts:
        - asset: assets/fonts/MyFlutterApp9.ttf
    - family: MyFlutterApp11
      fonts:
        - asset: assets/fonts/MyFlutterApp11.ttf
